// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/admin/recent-products': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/recent-products.get').default>>>>
    }
    '/api/admin/recent-users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/recent-users.get').default>>>>
    }
    '/api/admin/stats': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/stats.get').default>>>>
    }
    '/api/ads/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ads/create.post').default>>>>
    }
    '/api/ads/sponsored': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ads/sponsored.get').default>>>>
    }
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/me.get').default>>>>
    }
    '/api/auth/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/register.post').default>>>>
    }
    '/api/delivery/fees': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/delivery/fees.post').default>>>>
    }
    '/api/favorites/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/favorites/[id].delete').default>>>>
    }
    '/api/favorites': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/favorites/index.get').default>>>>
    }
    '/api/offers/list': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/offers/list.get').default>>>>
    }
    '/api/offers/publish': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/offers/publish').default>>>>
    }
    '/api/payments/initiate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/payments/initiate.post').default>>>>
    }
    '/api/payments/status/:transaction_id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/payments/status/[transaction_id].get').default>>>>
    }
    '/api/products/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/[id].put').default>>>>
    }
    '/api/products/add': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/add.post').default>>>>
    }
    '/api/products/compare': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/compare.post').default>>>>
    }
    '/api/products/delete-all': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/delete-all').default>>>>
    }
    '/api/products/list': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/list.get').default>>>>
    }
    '/api/sales/list': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sales/list.get').default>>>>
    }
    '/api/transactions/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/transactions/[id].delete').default>>>>
    }
    '/api/transactions': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/transactions/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/transactions/index.post').default>>>>
    }
    '/api/users/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[id].put').default>>>>
    }
    '/api/users/:id/role': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[id]/role.put').default>>>>
    }
    '/api/users/avatar': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/avatar.patch').default>>>>
    }
    '/api/users/delete-all': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/delete-all').default>>>>
    }
    '/api/users/list': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/list.get').default>>>>
    }
    '/api/users/profile': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/profile.get').default>>>>
    }
    '/api/users/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/register.post').default>>>>
    }
    '/api/users/roles': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/roles.get').default>>>>
    }
    '/api/users/stats': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/stats.get').default>>>>
    }
    '/api/wallet/topup': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/wallet/topup.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}