// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 04/02/2025 20:07:35
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/home/project/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/project/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/project/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/project/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/project/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/project/plugins/**/*.{js,ts,mjs}","/home/project/composables/**/*.{js,ts,mjs}","/home/project/utils/**/*.{js,ts,mjs}","/home/project/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/project/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/project/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["darkMode"] = ["selector","[class~=\"dark\"]"];;return cfg;})();

export default resolvedConfig;