// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 04/02/2025 21:59:51
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/thier/Documents/agroproject/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/thier/Documents/agroproject/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/thier/Documents/agroproject/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/thier/Documents/agroproject/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/thier/Documents/agroproject/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/thier/Documents/agroproject/plugins/**/*.{js,ts,mjs}","C:/Users/thier/Documents/agroproject/composables/**/*.{js,ts,mjs}","C:/Users/thier/Documents/agroproject/utils/**/*.{js,ts,mjs}","C:/Users/thier/Documents/agroproject/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/thier/Documents/agroproject/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/thier/Documents/agroproject/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["darkMode"] = ["selector","[class~=\"dark\"]"];;return cfg;})();

export default resolvedConfig;