
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'CompanyPresentation': typeof import("../components/CompanyPresentation.vue")['default']
    'ImageWithFallback': typeof import("../components/ImageWithFallback.vue")['default']
    'TheFooter': typeof import("../components/TheFooter.vue")['default']
    'TheHeader': typeof import("../components/TheHeader.vue")['default']
    'UnderConstruction': typeof import("../components/UnderConstruction.vue")['default']
    'AdminRoleSelect': typeof import("../components/admin/RoleSelect.vue")['default']
    'AdminUserEdit': typeof import("../components/admin/UserEdit.vue")['default']
    'AuthLoginForm': typeof import("../components/auth/LoginForm.vue")['default']
    'AuthRegisterForm': typeof import("../components/auth/RegisterForm.vue")['default']
    'ChatWindow': typeof import("../components/chat/ChatWindow.vue")['default']
    'CommonImageUpload': typeof import("../components/common/ImageUpload.vue")['default']
    'EquipmentRent': typeof import("../components/equipment/EquipmentRent.vue")['default']
    'IconsInfoIcon': typeof import("../components/icons/InfoIcon.vue")['default']
    'NavigationUserMenu': typeof import("../components/navigation/UserMenu.vue")['default']
    'PaymentCheckout': typeof import("../components/payment/Checkout.vue")['default']
    'ReviewsReviewForm': typeof import("../components/reviews/ReviewForm.vue")['default']
    'ReviewsReviewList': typeof import("../components/reviews/ReviewList.vue")['default']
    'Subscription': typeof import("../components/subscription/Subscription.vue")['default']
    'TrainingList': typeof import("../components/training/TrainingList.vue")['default']
    'TransactionHistory': typeof import("../components/transaction/TransactionHistory.vue")['default']
    'UserProfile': typeof import("../components/user/UserProfile.vue")['default']
    'WalletCard': typeof import("../components/wallet/WalletCard.vue")['default']
    'WalletTopUp': typeof import("../components/wallet/WalletTopUp.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'ColorScheme': typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyCompanyPresentation': typeof import("../components/CompanyPresentation.vue")['default']
    'LazyImageWithFallback': typeof import("../components/ImageWithFallback.vue")['default']
    'LazyTheFooter': typeof import("../components/TheFooter.vue")['default']
    'LazyTheHeader': typeof import("../components/TheHeader.vue")['default']
    'LazyUnderConstruction': typeof import("../components/UnderConstruction.vue")['default']
    'LazyAdminRoleSelect': typeof import("../components/admin/RoleSelect.vue")['default']
    'LazyAdminUserEdit': typeof import("../components/admin/UserEdit.vue")['default']
    'LazyAuthLoginForm': typeof import("../components/auth/LoginForm.vue")['default']
    'LazyAuthRegisterForm': typeof import("../components/auth/RegisterForm.vue")['default']
    'LazyChatWindow': typeof import("../components/chat/ChatWindow.vue")['default']
    'LazyCommonImageUpload': typeof import("../components/common/ImageUpload.vue")['default']
    'LazyEquipmentRent': typeof import("../components/equipment/EquipmentRent.vue")['default']
    'LazyIconsInfoIcon': typeof import("../components/icons/InfoIcon.vue")['default']
    'LazyNavigationUserMenu': typeof import("../components/navigation/UserMenu.vue")['default']
    'LazyPaymentCheckout': typeof import("../components/payment/Checkout.vue")['default']
    'LazyReviewsReviewForm': typeof import("../components/reviews/ReviewForm.vue")['default']
    'LazyReviewsReviewList': typeof import("../components/reviews/ReviewList.vue")['default']
    'LazySubscription': typeof import("../components/subscription/Subscription.vue")['default']
    'LazyTrainingList': typeof import("../components/training/TrainingList.vue")['default']
    'LazyTransactionHistory': typeof import("../components/transaction/TransactionHistory.vue")['default']
    'LazyUserProfile': typeof import("../components/user/UserProfile.vue")['default']
    'LazyWalletCard': typeof import("../components/wallet/WalletCard.vue")['default']
    'LazyWalletTopUp': typeof import("../components/wallet/WalletTopUp.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyColorScheme': typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const CompanyPresentation: typeof import("../components/CompanyPresentation.vue")['default']
export const ImageWithFallback: typeof import("../components/ImageWithFallback.vue")['default']
export const TheFooter: typeof import("../components/TheFooter.vue")['default']
export const TheHeader: typeof import("../components/TheHeader.vue")['default']
export const UnderConstruction: typeof import("../components/UnderConstruction.vue")['default']
export const AdminRoleSelect: typeof import("../components/admin/RoleSelect.vue")['default']
export const AdminUserEdit: typeof import("../components/admin/UserEdit.vue")['default']
export const AuthLoginForm: typeof import("../components/auth/LoginForm.vue")['default']
export const AuthRegisterForm: typeof import("../components/auth/RegisterForm.vue")['default']
export const ChatWindow: typeof import("../components/chat/ChatWindow.vue")['default']
export const CommonImageUpload: typeof import("../components/common/ImageUpload.vue")['default']
export const EquipmentRent: typeof import("../components/equipment/EquipmentRent.vue")['default']
export const IconsInfoIcon: typeof import("../components/icons/InfoIcon.vue")['default']
export const NavigationUserMenu: typeof import("../components/navigation/UserMenu.vue")['default']
export const PaymentCheckout: typeof import("../components/payment/Checkout.vue")['default']
export const ReviewsReviewForm: typeof import("../components/reviews/ReviewForm.vue")['default']
export const ReviewsReviewList: typeof import("../components/reviews/ReviewList.vue")['default']
export const Subscription: typeof import("../components/subscription/Subscription.vue")['default']
export const TrainingList: typeof import("../components/training/TrainingList.vue")['default']
export const TransactionHistory: typeof import("../components/transaction/TransactionHistory.vue")['default']
export const UserProfile: typeof import("../components/user/UserProfile.vue")['default']
export const WalletCard: typeof import("../components/wallet/WalletCard.vue")['default']
export const WalletTopUp: typeof import("../components/wallet/WalletTopUp.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const ColorScheme: typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyCompanyPresentation: typeof import("../components/CompanyPresentation.vue")['default']
export const LazyImageWithFallback: typeof import("../components/ImageWithFallback.vue")['default']
export const LazyTheFooter: typeof import("../components/TheFooter.vue")['default']
export const LazyTheHeader: typeof import("../components/TheHeader.vue")['default']
export const LazyUnderConstruction: typeof import("../components/UnderConstruction.vue")['default']
export const LazyAdminRoleSelect: typeof import("../components/admin/RoleSelect.vue")['default']
export const LazyAdminUserEdit: typeof import("../components/admin/UserEdit.vue")['default']
export const LazyAuthLoginForm: typeof import("../components/auth/LoginForm.vue")['default']
export const LazyAuthRegisterForm: typeof import("../components/auth/RegisterForm.vue")['default']
export const LazyChatWindow: typeof import("../components/chat/ChatWindow.vue")['default']
export const LazyCommonImageUpload: typeof import("../components/common/ImageUpload.vue")['default']
export const LazyEquipmentRent: typeof import("../components/equipment/EquipmentRent.vue")['default']
export const LazyIconsInfoIcon: typeof import("../components/icons/InfoIcon.vue")['default']
export const LazyNavigationUserMenu: typeof import("../components/navigation/UserMenu.vue")['default']
export const LazyPaymentCheckout: typeof import("../components/payment/Checkout.vue")['default']
export const LazyReviewsReviewForm: typeof import("../components/reviews/ReviewForm.vue")['default']
export const LazyReviewsReviewList: typeof import("../components/reviews/ReviewList.vue")['default']
export const LazySubscription: typeof import("../components/subscription/Subscription.vue")['default']
export const LazyTrainingList: typeof import("../components/training/TrainingList.vue")['default']
export const LazyTransactionHistory: typeof import("../components/transaction/TransactionHistory.vue")['default']
export const LazyUserProfile: typeof import("../components/user/UserProfile.vue")['default']
export const LazyWalletCard: typeof import("../components/wallet/WalletCard.vue")['default']
export const LazyWalletTopUp: typeof import("../components/wallet/WalletTopUp.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyColorScheme: typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
